//const json1 = "{
//					"employees": [{
//							"firstName": "Bill",
//							"lastName": "Gates"
//						},
//						{
//							"firstName": "George",
//							"lastName": "Bush"
//						},
//						{
//							"firstName": "Thomas",
//							"lastName": "Carter"
//						}
//					]
//				}"
var aajson = {
	"code":0,
	"data":{
		"morning":"0",
		"afternoon":"1"
	}
}


var ajson = {
	"code":0,
	"data":{
		"asuccess":[{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"1",
			"peoples":"10"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"2",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"3",
			"peoples":"6"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"4",
			"peoples":"5"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"5",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"6",
			"peoples":"1"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"1",
			"peoples":"10"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"2",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"3",
			"peoples":"6"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"4",
			"peoples":"5"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"5",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"6",
			"peoples":"1"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"1",
			"peoples":"10"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"2",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"3",
			"peoples":"6"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"4",
			"peoples":"5"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"5",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"6",
			"peoples":"1"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"1",
			"peoples":"10"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"2",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"3",
			"peoples":"6"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"4",
			"peoples":"5"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"5",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"6",
			"peoples":"1"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"1",
			"peoples":"10"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"2",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"3",
			"peoples":"6"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"4",
			"peoples":"5"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"5",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"6",
			"peoples":"1"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"1",
			"peoples":"10"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"2",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"3",
			"peoples":"6"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"4",
			"peoples":"5"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"5",
			"peoples":"9"
		},{
			"time_year":"2018",
			"time_month":"12",
			"time_day":"6",
			"peoples":"1"
		}]
	}
}
